### ISSUE TITLE
model2.mat and training data 

### ISSUE THREAD

**Issue by liujiaoshou17** [pui-nantheera/volcano_deform_detection#1]
How to get model2.mat and training data without @bristol.ac.uk school email？

**Comment by pui-nantheera** [comment]
I've updated link address. Can you please try again?

**Comment by liujiaoshou17** [comment]
> 
> 
> I've updated link address. Can you please try again?

Thank you very much for updating  link address. 
Recently I have read a lot of your papers on using ConvNet to monitor volcanic deformation, and I feel very interested in your related research.I also want to do research in this area, but I lack data sets.Can you give me some suggestions?

**Comment by pui-nantheera** [comment]
https://uob-my.sharepoint.com/:f:/g/personal/eexna_bristol_ac_uk/Ehx_Z7LfNE9Pqo_1CJzMKPcB6-d3nlHGyOkiz4cdvDz4OQ?e=vOxtlh

https://uob-my.sharepoint.com/:f:/g/personal/eexna_bristol_ac_uk/Ep18o6w7FUZJuY0nYcyOOxgBccF8M4BX9od3goTR-M8ejA?e=wEgb1m
