### ISSUE TITLE
Model download Links Broken/expired

### ISSUE THREAD

**Issue by drotheram** [pui-nantheera/volcano_deform_detection#3]
Greetings Dr. Nantheera, 

I would like to try running your Volcanic Deformation Detection tool but it appears the links to the pre-trained models are either broken or expired. Would it be possible to re-post these models? Or potentially add them to the repo as 'release assets'?

Many thanks!

**Comment by pui-nantheera** [comment]
Thanks for suggestion. I've included models with the release.

**Comment by drotheram** [comment]
Thank you!
